site_name: Injector
site_description: 'Zero-overhead and minimalist dependency injection library'
site_author: 'Skullabs Contributors'
site_url: 'https://skullabs.github.io/injector/'

theme:
  name: 'material'
  palette:
    primary: 'light blue'
    accent: 'blue grey'
  feature:
    tabs: true


docs_dir: docs_src
site_dir: docs
extra_css:
  - custom.css

repo_name: 'skullabs/injector'
repo_url: 'https://github.com/Skullabs/injector'

copyright: 'Copyright &copy; 2018 - 2021 Skullabs Contributors'

# Plugins
plugins:
  - search
  - bootstrap-tables

# Extensions
markdown_extensions:
  - admonition
#  - codehilite:
#      guess_lang: false
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.superfences
#  - toc:
#      permalink: true
